//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhanMemQuanLyHocSinhTHPT_ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiemSo
    {
        public string MaHS { get; set; }
        public string MaMH { get; set; }
        public string MaHK { get; set; }
        public Nullable<double> DiemMieng { get; set; }
        public Nullable<double> Diem15PhutLan1 { get; set; }
        public Nullable<double> Diem15PhutLan2 { get; set; }
        public Nullable<double> Diem1TietLan1 { get; set; }
        public Nullable<double> Diem1TietLan2 { get; set; }
        public Nullable<double> DiemThi { get; set; }
    
        public virtual HocKy HocKy { get; set; }
        public virtual HocSinh HocSinh { get; set; }
        public virtual MonHoc MonHoc { get; set; }
    }
}
